### ISSUE TITLE
启动项目报错 Browser.setDownloadBehavior

### ISSUE THREAD

**Issue by 519544044** [Zdelta/SeleniumCrawler#1]
安装了对应的 chrome版本 ，启动报错。求解决，有偿请教。

**Comment by 519544044** [comment]
{"code":-32601,"message":"'Browser.setDownloadBehavior' wasn't found"}

**Comment by Zdelta** [comment]
> {"code":-32601,"message":"'Browser.setDownloadBehavior' wasn't found"}

环境冲突了? 换台电脑试试

**Comment by 519544044** [comment]
> > {"code":-32601,"message":"'Browser.setDownloadBehavior' wasn't found"}
> 
> 环境冲突了? 换台电脑试试

版本调整了一下就OK了
